name: Run layoff-scraper

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run layoff-scraper
      run: Rscript layoff-scraper.R
    - uses: actions/setup-R@v1
      with:
        r-version: 4.0.2
        r-packages: tidyverse, rvest, janitor, xml2, tidyr, pdftools, lubridate, stringr, googlesheets4, tidycensus
