name: Run layoff scraper

on:
  schedule:
    - cron: '* * * * *'

jobs:
  autoscrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
    
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("janitor")'
          R -e 'install.packages("xml2")'
          R -e 'install.packages("tidyr")'
          R -e 'install.packages("pdftools")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("googlesheets4")'
          R -e 'install.packages("tidycensus")'
        
      - name: Scrape
        run: Rscript layoff-scraper.R
    
    
