on:
  schedule:
    - cron: '* * * * *'
    
  workflow_dispatch:
  
name: Run-layoff-scraper

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GSHEET_LAYOFFS_PASSWORD: ${{ secrets.GSHEET_LAYOFFS_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::rvest
            any::janitor
            any::xml2
            any::tidyr
            any::pdftools
            any::lubridate
            any::stringr
            any::tokencodr
            any::googlesheets4
            any::tidycensus
        
      - name: Scrape
        run: |
          Rscript "layoff-scraper.R"
    
    
