on:
  schedule:
    - cron: '0 12 * * *'
    
  workflow_dispatch:
  
name: Run-layoff-scraper

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
      GSHEET_LAYOFFS_PASSWORD: ${{ secrets.GSHEET_LAYOFFS_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::rvest
            any::janitor
            any::xml2
            any::tidyr
            any::pdftools
            any::lubridate
            any::stringr
            any::googlesheets4
            any::tidycensus
            any::remotes
            
      - name: install-tokencodr-package
        run: |
          echo 'remotes::install_github("jdtrat/tokencodr")' > install-packages.R
          Rscript install-packages.R
        
      - name: Scrape
        run: |
          Rscript "layoff-scraper.R"
    
    
